[book]
title   = "NeoPRISM Documentation"
authors = [  ]

[build]
build-dir = "book"

[preprocessor.cmdrun]
renderers = [ "html", "markdown" ]

[preprocessor.d2]
command  = "mdbook-d2"
renderer = [ "html", "markdown" ]

[output.html]

[output.markdown]

# NOTE: mdbook-linkcheck fails with the current build configuration. Revisit later.
# [output.linkcheck]
# follow-web-links = false           # enable this when checking broken links
# exclude          = [ 'localhost' ]
